#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Saturday 11 November 2023  21:28:41
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2023.3"
myNAME = "pyKlock"

[COLOUR]
foreground = "#ffffff"
background = "#80ff80"
transparent = "true"

[WINDOW]
width = 550
height = 200
x_pos = 1165.0
y_pos = -372.0

[TIME]
type = "Fuzzy Time"
