#   Configure file for pyKlock.py
#   (c) Kevin Scott   Written Sunday 10 December 2023  21:30:57
#
#   true and false are lower case
#
[INFO]
myVERSION = "2023.8.beta"
myNAME = "pyKlock"

[COLOUR]
foreground = "#8A2BE2"
background = "#8A2BE2"
transparent = true

[WINDOW]
width = 550
height = 600
x_pos = 1177.0
y_pos = -686.0

[TIME]
type = "Fuzzy Time"
