#   Configure file for pyKlock.py
#   (c) Kevin Scott   Written Sunday 12 November 2023  16:27:34
#
#   true and false are lower case
#
[INFO]
myVERSION = "2023.4"
myNAME = "pyKlock"

[COLOUR]
foreground = "#ffffff"
background = "#80ff80"
transparent = "true"

[WINDOW]
width = 550
height = 200
x_pos = 1070.0
y_pos = -363.0

[TIME]
type = "Local Time"
