#   Configure file for pyKlock.py
#   (c) Kevin Scott   Written Tuesday 21 November 2023  21:51:15
#
#   true and false are lower case
#
[INFO]
myVERSION = "2023.5"
myNAME = "pyKlock"

[COLOUR]
foreground = "#ffffff"
background = "#80ff80"
transparent = true

[WINDOW]
width = 550
height = 200
x_pos = 1184.0
y_pos = -436.0

[TIME]
type = "Fuzzy Time"
